### ISSUE TITLE
Turn off LEDs to enhance power savings

### ISSUE THREAD

**Issue by oliemery** [Hackuarium/simple-spectro#48]
Since the LEDs are not visible from the end user, they could be turned off (in particular during sleep) to save power and enhance battery life.
The LEDs are useful for debugging but not used/visible for the assembled version of the spectro. In case the light from these LEDs go through the cuvette (as it is the case with the laser-cut version without a case around the lower part of the cuvette), they may affect the readings in different ways since the colors of the LEDs while change whether the spectro is charging or not via usb for example (although I haven't tested for these effects I could see light through the cuvette in sleep mode in the dark)

**Comment by lpatiny** [comment]
Indeed the leds are useless and they are there in this first release. The new version do not have leds anymore.
